### ISSUE TITLE
Cannot read property 0 of null

### ISSUE THREAD

**Issue by piuccio** [ragingwind/semver-sort#3]
Hi, nice project.

I was trying to run this code

``` js
var tags = [
'v2.0.1',
'2.0.0-alpha2',
'v2.0-alpha',
'v1.1.1',
'v1.1.0',
'v1.0.2',
'v1.0.1',
'v1.0.1-beta.4',
'v1.0.1-beta.3',
'v1.0.1-beta.2',
'v2.0.0',
'v1.0.0-beta',
'v0.2.0',
'2.0.2',
'2.0.0-beta2',
'2.0.0-beta1',
'2.0.0-beta',
'2.0.0-alpha4',
'2.0.0-alpha3',
'v1.0.1-beta'
];

var semverSort = require('semver-sort');

console.log(semverSort.desc(tags));
```

And I get the exception

```
semver-sort/index.js:12
        var sv1 = semverRegex().exec(v1)[0] || v1;
                                        ^

TypeError: Cannot read property '0' of null
    at semver-sort/index.js:12:35
    at Array.sort (native)
    at sort (semver-sort/index.js:11:17)
    at Object.module.exports.desc (semver-sort/index.js:25:10)
    at Object.<anonymous> (bug.js:26:24)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

```

**Comment by ragingwind** [comment]
One of versions has invalid format for semver. Unfortunately, this module doesn't support to filter invalid semver string as input. You should make sure that passing valid semver strings to this module. FYI, we use this regexp, https://github.com/sindresorhus/semver-regex/blob/master/index.js#L3
